import type { Metadata } from "next";
import { notoSans } from "@/app/ui/fonts";
import '@/app/ui/globals.css';
import BottomNav from "@/app/ui/bottom-nav";

export const metadata: Metadata = {
  title: {
    template: "%s | TikTok Clone",
    default: "TikTok Clone",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased m-0 h-screen`}
      >
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
